USE test_db
GO

CREATE TABLE TB_CUSTOMER
(
    ID_CUSTOMER INT IDENTITY(1,1),
    NAME VARCHAR(250) NOT NULL
)

INSERT INTO TB_CUSTOMER (NAME) VALUES ('FERNANDO M. OLIVEIRA')
INSERT INTO TB_CUSTOMER (NAME) VALUES ('BILL GATES')
INSERT INTO TB_CUSTOMER (NAME) VALUES ('STEVE JOBS')
INSERT INTO TB_CUSTOMER (NAME) VALUES ('EDDIE VEDDER')
INSERT INTO TB_CUSTOMER (NAME) VALUES ('DAVID GILMOUR')

SELECT TOP (10)
    [ID_CUSTOMER], [NAME]
FROM
    [test_db].[dbo].[TB_CUSTOMER]